ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TURN_ANGLE: 30  # action: turn left, turn right (degrees)
  TILT_ANGLE: 30  # action: look up, look down (degrees)
  TURN_ANGLE_S: 15 # action: turn left small, turn right small (degrees)
#  TILT_ANGLE_S: 10 # action: look up small, look down small
  ACTION_SPACE_CONFIG: "v0"
  NUM_AGENTS: 2
  AGENTS: ["AGENT_0", "AGENT_1"]
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
  SCENE_DATASET: "data/scene_datasets/hm3d_v0.2/hm3d_annotated_basis.scene_dataset_config.json"
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SENSORS: ['OBJECTGOAL_SENSOR', 'GPS_SENSOR', 'COMPASS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val
  DATA_PATH: "data/datasets/objectnav/hm3d/v2/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
